-- 002_refunds.sql
-- Forward-only migration. Do NOT edit this file after it has been applied.
--
-- A refund records that a merchant/admin returned money for an order as store credit.
-- The refund row is the audit source of truth; every refund creates exactly one positive
-- store_credit_ledger entry for the order's customer, and points at it via ledger_entry_id.

CREATE TABLE refunds (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id         UUID NOT NULL REFERENCES orders(id),
  amount_cents     INTEGER NOT NULL CHECK (amount_cents > 0),
  reason           TEXT NOT NULL,
  created_by       UUID NOT NULL REFERENCES users(id),     -- the merchant/admin who issued it
  ledger_entry_id  UUID NOT NULL REFERENCES store_credit_ledger(id),
  idempotency_key  TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX refunds_order_id_idx ON refunds (order_id);

-- A retried refund that reuses the same client key must not double-credit. Partial unique
-- index so refunds without a key (idempotency_key IS NULL) are still allowed.
CREATE UNIQUE INDEX refunds_order_idempotency_uniq
  ON refunds (order_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;
