-- 003_products.sql
-- Forward-only migration. Do NOT edit this file after it has been applied.
--
-- Introduces a merchant-owned product catalog and links order line items to it. Existing line
-- items keep working: product_id is nullable, and name/unit_price_cents remain the at-purchase
-- snapshot (copied at order time, never mutated when a product later changes price or is retired).

CREATE TABLE products (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  merchant_id  UUID NOT NULL REFERENCES users(id),
  name         TEXT NOT NULL,
  description  TEXT,
  category     TEXT NOT NULL,
  price_cents  INTEGER NOT NULL CHECK (price_cents >= 0),
  active       BOOLEAN NOT NULL DEFAULT true,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX products_merchant_id_idx ON products (merchant_id);

ALTER TABLE order_items
  ADD COLUMN product_id UUID REFERENCES products(id);

CREATE INDEX order_items_product_id_idx ON order_items (product_id);
